package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer claveCategoria;
     private String categoria;
     private String descripcion;
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);

    public Categorias() {
    }

	
    public Categorias(String categoria) {
        this.categoria = categoria;
    }
    public Categorias(String categoria, String descripcion, Set<Detallesproductos> detallesproductoses) {
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.detallesproductoses = detallesproductoses;
    }
   
    public Integer getClaveCategoria() {
        return this.claveCategoria;
    }
    
    public void setClaveCategoria(Integer claveCategoria) {
        this.claveCategoria = claveCategoria;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }




}


