package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Codigospostales generated by hbm2java
 */
public class Codigospostales  implements java.io.Serializable {


     private Integer claveCodigoPostal;
     private String codigoPostal;
     private String descripcion;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Codigospostales() {
    }

	
    public Codigospostales(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Codigospostales(String codigoPostal, String descripcion, Set<Municipios> municipioses) {
       this.codigoPostal = codigoPostal;
       this.descripcion = descripcion;
       this.municipioses = municipioses;
    }
   
    public Integer getClaveCodigoPostal() {
        return this.claveCodigoPostal;
    }
    
    public void setClaveCodigoPostal(Integer claveCodigoPostal) {
        this.claveCodigoPostal = claveCodigoPostal;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }




}


