package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprasclientes generated by hbm2java
 */
public class Comprasclientes  implements java.io.Serializable {


     private Integer claveCompraCliente;
     private Formaspagos formaspagos;
     private Historiales historiales;
     private Descuentos descuentos;
     private Date fechaCompra;
     private float subtotal;
     private float total;
     private Set<Facturas> facturases = new HashSet<Facturas>(0);
     private Set<Detallescompras> detallescomprases = new HashSet<Detallescompras>(0);

    public Comprasclientes() {
    }

	
    public Comprasclientes(Formaspagos formaspagos, Historiales historiales, Descuentos descuentos, Date fechaCompra, float subtotal, float total) {
        this.formaspagos = formaspagos;
        this.historiales = historiales;
        this.descuentos = descuentos;
        this.fechaCompra = fechaCompra;
        this.subtotal = subtotal;
        this.total = total;
    }
    public Comprasclientes(Formaspagos formaspagos, Historiales historiales, Descuentos descuentos, Date fechaCompra, float subtotal, float total, Set<Facturas> facturases, Set<Detallescompras> detallescomprases) {
       this.formaspagos = formaspagos;
       this.historiales = historiales;
       this.descuentos = descuentos;
       this.fechaCompra = fechaCompra;
       this.subtotal = subtotal;
       this.total = total;
       this.facturases = facturases;
       this.detallescomprases = detallescomprases;
    }
   
    public Integer getClaveCompraCliente() {
        return this.claveCompraCliente;
    }
    
    public void setClaveCompraCliente(Integer claveCompraCliente) {
        this.claveCompraCliente = claveCompraCliente;
    }
    public Formaspagos getFormaspagos() {
        return this.formaspagos;
    }
    
    public void setFormaspagos(Formaspagos formaspagos) {
        this.formaspagos = formaspagos;
    }
    public Historiales getHistoriales() {
        return this.historiales;
    }
    
    public void setHistoriales(Historiales historiales) {
        this.historiales = historiales;
    }
    public Descuentos getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Descuentos descuentos) {
        this.descuentos = descuentos;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public Set<Facturas> getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set<Facturas> facturases) {
        this.facturases = facturases;
    }
    public Set<Detallescompras> getDetallescomprases() {
        return this.detallescomprases;
    }
    
    public void setDetallescomprases(Set<Detallescompras> detallescomprases) {
        this.detallescomprases = detallescomprases;
    }




}


