package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Descuentos generated by hbm2java
 */
public class Descuentos  implements java.io.Serializable {


     private Integer claveDescuento;
     private float descuento;
     private String descripcion;
     private Set<Comprasclientes> comprasclienteses = new HashSet<Comprasclientes>(0);

    public Descuentos() {
    }

	
    public Descuentos(float descuento) {
        this.descuento = descuento;
    }
    public Descuentos(float descuento, String descripcion, Set<Comprasclientes> comprasclienteses) {
       this.descuento = descuento;
       this.descripcion = descripcion;
       this.comprasclienteses = comprasclienteses;
    }
   
    public Integer getClaveDescuento() {
        return this.claveDescuento;
    }
    
    public void setClaveDescuento(Integer claveDescuento) {
        this.claveDescuento = claveDescuento;
    }
    public float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(float descuento) {
        this.descuento = descuento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Comprasclientes> getComprasclienteses() {
        return this.comprasclienteses;
    }
    
    public void setComprasclienteses(Set<Comprasclientes> comprasclienteses) {
        this.comprasclienteses = comprasclienteses;
    }




}


