package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Detallesproductos generated by hbm2java
 */
public class Detallesproductos  implements java.io.Serializable {


     private Integer claveProducto;
     private Categorias categorias;
     private Productos productos;
     private Empresasproveedoras empresasproveedoras;
     private Marcas marcas;
     private Sucursales sucursales;
     private Calidades calidades;
     private Unidadesmediciones unidadesmediciones;
     private float precioUnitario;
     private Date fechaRegistro;
     private int existencias;
     private boolean activo;

    public Detallesproductos() {
    }

    public Detallesproductos(Categorias categorias, Productos productos, Empresasproveedoras empresasproveedoras, Marcas marcas, Sucursales sucursales, Calidades calidades, Unidadesmediciones unidadesmediciones, float precioUnitario, Date fechaRegistro, int existencias, boolean activo) {
       this.categorias = categorias;
       this.productos = productos;
       this.empresasproveedoras = empresasproveedoras;
       this.marcas = marcas;
       this.sucursales = sucursales;
       this.calidades = calidades;
       this.unidadesmediciones = unidadesmediciones;
       this.precioUnitario = precioUnitario;
       this.fechaRegistro = fechaRegistro;
       this.existencias = existencias;
       this.activo = activo;
    }
   
    public Integer getClaveProducto() {
        return this.claveProducto;
    }
    
    public void setClaveProducto(Integer claveProducto) {
        this.claveProducto = claveProducto;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Empresasproveedoras getEmpresasproveedoras() {
        return this.empresasproveedoras;
    }
    
    public void setEmpresasproveedoras(Empresasproveedoras empresasproveedoras) {
        this.empresasproveedoras = empresasproveedoras;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Calidades getCalidades() {
        return this.calidades;
    }
    
    public void setCalidades(Calidades calidades) {
        this.calidades = calidades;
    }
    public Unidadesmediciones getUnidadesmediciones() {
        return this.unidadesmediciones;
    }
    
    public void setUnidadesmediciones(Unidadesmediciones unidadesmediciones) {
        this.unidadesmediciones = unidadesmediciones;
    }
    public float getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(float precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


