package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA



/**
 * Detallescompras generated by hbm2java
 */
public class Detallescompras  implements java.io.Serializable {


     private DetallescomprasId id;
     private Productos productos;
     private Comprasclientes comprasclientes;
     private int cantidad;

    public Detallescompras() {
    }

    public Detallescompras(DetallescomprasId id, Productos productos, Comprasclientes comprasclientes, int cantidad) {
       this.id = id;
       this.productos = productos;
       this.comprasclientes = comprasclientes;
       this.cantidad = cantidad;
    }
   
    public DetallescomprasId getId() {
        return this.id;
    }
    
    public void setId(DetallescomprasId id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Comprasclientes getComprasclientes() {
        return this.comprasclientes;
    }
    
    public void setComprasclientes(Comprasclientes comprasclientes) {
        this.comprasclientes = comprasclientes;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


