package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA



/**
 * DetallescomprasId generated by hbm2java
 */
public class DetallescomprasId  implements java.io.Serializable {


     private int claveDetallesCompra;
     private int compraCliente;
     private int producto;

    public DetallescomprasId() {
    }

    public DetallescomprasId(int claveDetallesCompra, int compraCliente, int producto) {
       this.claveDetallesCompra = claveDetallesCompra;
       this.compraCliente = compraCliente;
       this.producto = producto;
    }
   
    public int getClaveDetallesCompra() {
        return this.claveDetallesCompra;
    }
    
    public void setClaveDetallesCompra(int claveDetallesCompra) {
        this.claveDetallesCompra = claveDetallesCompra;
    }
    public int getCompraCliente() {
        return this.compraCliente;
    }
    
    public void setCompraCliente(int compraCliente) {
        this.compraCliente = compraCliente;
    }
    public int getProducto() {
        return this.producto;
    }
    
    public void setProducto(int producto) {
        this.producto = producto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallescomprasId) ) return false;
		 DetallescomprasId castOther = ( DetallescomprasId ) other; 
         
		 return (this.getClaveDetallesCompra()==castOther.getClaveDetallesCompra())
 && (this.getCompraCliente()==castOther.getCompraCliente())
 && (this.getProducto()==castOther.getProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClaveDetallesCompra();
         result = 37 * result + this.getCompraCliente();
         result = 37 * result + this.getProducto();
         return result;
   }   


}


