package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Direcciones generated by hbm2java
 */
public class Direcciones  implements java.io.Serializable {


     private Integer claveDireccion;
     private Estados estados;
     private String calle;
     private String numeroInterno;
     private String numeroExterno;
     private Set<Empresasproveedoras> empresasproveedorases = new HashSet<Empresasproveedoras>(0);

    public Direcciones() {
    }

	
    public Direcciones(Estados estados, String calle, String numeroInterno, String numeroExterno) {
        this.estados = estados;
        this.calle = calle;
        this.numeroInterno = numeroInterno;
        this.numeroExterno = numeroExterno;
    }
    public Direcciones(Estados estados, String calle, String numeroInterno, String numeroExterno, Set<Empresasproveedoras> empresasproveedorases) {
       this.estados = estados;
       this.calle = calle;
       this.numeroInterno = numeroInterno;
       this.numeroExterno = numeroExterno;
       this.empresasproveedorases = empresasproveedorases;
    }
   
    public Integer getClaveDireccion() {
        return this.claveDireccion;
    }
    
    public void setClaveDireccion(Integer claveDireccion) {
        this.claveDireccion = claveDireccion;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumeroInterno() {
        return this.numeroInterno;
    }
    
    public void setNumeroInterno(String numeroInterno) {
        this.numeroInterno = numeroInterno;
    }
    public String getNumeroExterno() {
        return this.numeroExterno;
    }
    
    public void setNumeroExterno(String numeroExterno) {
        this.numeroExterno = numeroExterno;
    }
    public Set<Empresasproveedoras> getEmpresasproveedorases() {
        return this.empresasproveedorases;
    }
    
    public void setEmpresasproveedorases(Set<Empresasproveedoras> empresasproveedorases) {
        this.empresasproveedorases = empresasproveedorases;
    }




}


