package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Domicilios generated by hbm2java
 */
public class Domicilios  implements java.io.Serializable {


     private Integer claveDomicilio;
     private Municipios municipios;
     private String domicilio;
     private String numeroInterno;
     private String numeroExterno;
     private Set<Personas> personases = new HashSet<Personas>(0);

    public Domicilios() {
    }

	
    public Domicilios(Municipios municipios, String domicilio, String numeroInterno, String numeroExterno) {
        this.municipios = municipios;
        this.domicilio = domicilio;
        this.numeroInterno = numeroInterno;
        this.numeroExterno = numeroExterno;
    }
    public Domicilios(Municipios municipios, String domicilio, String numeroInterno, String numeroExterno, Set<Personas> personases) {
       this.municipios = municipios;
       this.domicilio = domicilio;
       this.numeroInterno = numeroInterno;
       this.numeroExterno = numeroExterno;
       this.personases = personases;
    }
   
    public Integer getClaveDomicilio() {
        return this.claveDomicilio;
    }
    
    public void setClaveDomicilio(Integer claveDomicilio) {
        this.claveDomicilio = claveDomicilio;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getNumeroInterno() {
        return this.numeroInterno;
    }
    
    public void setNumeroInterno(String numeroInterno) {
        this.numeroInterno = numeroInterno;
    }
    public String getNumeroExterno() {
        return this.numeroExterno;
    }
    
    public void setNumeroExterno(String numeroExterno) {
        this.numeroExterno = numeroExterno;
    }
    public Set<Personas> getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set<Personas> personases) {
        this.personases = personases;
    }




}


