package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresasproveedoras generated by hbm2java
 */
public class Empresasproveedoras  implements java.io.Serializable {


     private Integer claveEmpresa;
     private Direcciones direcciones;
     private String rfc;
     private String nombre;
     private String razonSocial;
     private Date fechaRegistro;
     private boolean activo;
     private String telefono;
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);
     private Set<Contactos> contactoses = new HashSet<Contactos>(0);

    public Empresasproveedoras() {
    }

	
    public Empresasproveedoras(Direcciones direcciones, String rfc, String nombre, String razonSocial, Date fechaRegistro, boolean activo) {
        this.direcciones = direcciones;
        this.rfc = rfc;
        this.nombre = nombre;
        this.razonSocial = razonSocial;
        this.fechaRegistro = fechaRegistro;
        this.activo = activo;
    }
    public Empresasproveedoras(Direcciones direcciones, String rfc, String nombre, String razonSocial, Date fechaRegistro, boolean activo, String telefono, Set<Detallesproductos> detallesproductoses, Set<Contactos> contactoses) {
       this.direcciones = direcciones;
       this.rfc = rfc;
       this.nombre = nombre;
       this.razonSocial = razonSocial;
       this.fechaRegistro = fechaRegistro;
       this.activo = activo;
       this.telefono = telefono;
       this.detallesproductoses = detallesproductoses;
       this.contactoses = contactoses;
    }
   
    public Integer getClaveEmpresa() {
        return this.claveEmpresa;
    }
    
    public void setClaveEmpresa(Integer claveEmpresa) {
        this.claveEmpresa = claveEmpresa;
    }
    public Direcciones getDirecciones() {
        return this.direcciones;
    }
    
    public void setDirecciones(Direcciones direcciones) {
        this.direcciones = direcciones;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }
    public Set<Contactos> getContactoses() {
        return this.contactoses;
    }
    
    public void setContactoses(Set<Contactos> contactoses) {
        this.contactoses = contactoses;
    }




}


