package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private Integer claveEstado;
     private String estado;
     private String descripcion;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);
     private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);

    public Estados() {
    }

	
    public Estados(String estado) {
        this.estado = estado;
    }
    public Estados(String estado, String descripcion, Set<Municipios> municipioses, Set<Direcciones> direccioneses) {
       this.estado = estado;
       this.descripcion = descripcion;
       this.municipioses = municipioses;
       this.direccioneses = direccioneses;
    }
   
    public Integer getClaveEstado() {
        return this.claveEstado;
    }
    
    public void setClaveEstado(Integer claveEstado) {
        this.claveEstado = claveEstado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }
    public Set<Direcciones> getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set<Direcciones> direccioneses) {
        this.direccioneses = direccioneses;
    }




}


