package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer claveFactura;
     private Historiales historiales;
     private Comprasclientes comprasclientes;
     private Date fechaFactura;

    public Facturas() {
    }

    public Facturas(Historiales historiales, Comprasclientes comprasclientes, Date fechaFactura) {
       this.historiales = historiales;
       this.comprasclientes = comprasclientes;
       this.fechaFactura = fechaFactura;
    }
   
    public Integer getClaveFactura() {
        return this.claveFactura;
    }
    
    public void setClaveFactura(Integer claveFactura) {
        this.claveFactura = claveFactura;
    }
    public Historiales getHistoriales() {
        return this.historiales;
    }
    
    public void setHistoriales(Historiales historiales) {
        this.historiales = historiales;
    }
    public Comprasclientes getComprasclientes() {
        return this.comprasclientes;
    }
    
    public void setComprasclientes(Comprasclientes comprasclientes) {
        this.comprasclientes = comprasclientes;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }




}


