package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer claveMarca;
     private String marca;
     private String descripcion;
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);

    public Marcas() {
    }

	
    public Marcas(String marca, String descripcion) {
        this.marca = marca;
        this.descripcion = descripcion;
    }
    public Marcas(String marca, String descripcion, Set<Detallesproductos> detallesproductoses) {
       this.marca = marca;
       this.descripcion = descripcion;
       this.detallesproductoses = detallesproductoses;
    }
   
    public Integer getClaveMarca() {
        return this.claveMarca;
    }
    
    public void setClaveMarca(Integer claveMarca) {
        this.claveMarca = claveMarca;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }




}


