package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Presupuestos generated by hbm2java
 */
public class Presupuestos  implements java.io.Serializable {


     private Integer clave;
     private Clientes clientes;
     private Productos productos;
     private Date fechaPresupuesto;
     private float montoTotal;

    public Presupuestos() {
    }

    public Presupuestos(Clientes clientes, Productos productos, Date fechaPresupuesto, float montoTotal) {
       this.clientes = clientes;
       this.productos = productos;
       this.fechaPresupuesto = fechaPresupuesto;
       this.montoTotal = montoTotal;
    }
   
    public Integer getClave() {
        return this.clave;
    }
    
    public void setClave(Integer clave) {
        this.clave = clave;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Date getFechaPresupuesto() {
        return this.fechaPresupuesto;
    }
    
    public void setFechaPresupuesto(Date fechaPresupuesto) {
        this.fechaPresupuesto = fechaPresupuesto;
    }
    public float getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(float montoTotal) {
        this.montoTotal = montoTotal;
    }




}


