package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer claveProducto;
     private String nombre;
     private String imagen;
     private String descripcion;
     private Set<Presupuestos> presupuestoses = new HashSet<Presupuestos>(0);
     private Set<Detallescompras> detallescomprases = new HashSet<Detallescompras>(0);
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);

    public Productos() {
    }

	
    public Productos(String nombre) {
        this.nombre = nombre;
    }
    public Productos(String nombre, String imagen, String descripcion, Set<Presupuestos> presupuestoses, Set<Detallescompras> detallescomprases, Set<Detallesproductos> detallesproductoses) {
       this.nombre = nombre;
       this.imagen = imagen;
       this.descripcion = descripcion;
       this.presupuestoses = presupuestoses;
       this.detallescomprases = detallescomprases;
       this.detallesproductoses = detallesproductoses;
    }
   
    public Integer getClaveProducto() {
        return this.claveProducto;
    }
    
    public void setClaveProducto(Integer claveProducto) {
        this.claveProducto = claveProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Presupuestos> getPresupuestoses() {
        return this.presupuestoses;
    }
    
    public void setPresupuestoses(Set<Presupuestos> presupuestoses) {
        this.presupuestoses = presupuestoses;
    }
    public Set<Detallescompras> getDetallescomprases() {
        return this.detallescomprases;
    }
    
    public void setDetallescomprases(Set<Detallescompras> detallescomprases) {
        this.detallescomprases = detallescomprases;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }




}


