package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Integer claveSucursal;
     private String nombre;
     private String descripcion;
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Sucursales() {
    }

	
    public Sucursales(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Sucursales(String nombre, String descripcion, Set<Detallesproductos> detallesproductoses, Set<Usuarios> usuarioses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.detallesproductoses = detallesproductoses;
       this.usuarioses = usuarioses;
    }
   
    public Integer getClaveSucursal() {
        return this.claveSucursal;
    }
    
    public void setClaveSucursal(Integer claveSucursal) {
        this.claveSucursal = claveSucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


