package Model;
// Generated 18/08/2013 10:09:46 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Unidadesmediciones generated by hbm2java
 */
public class Unidadesmediciones  implements java.io.Serializable {


     private Integer claveUnidadMedicion;
     private String unidadMedicion;
     private String descripcion;
     private Set<Detallesproductos> detallesproductoses = new HashSet<Detallesproductos>(0);

    public Unidadesmediciones() {
    }

	
    public Unidadesmediciones(String unidadMedicion) {
        this.unidadMedicion = unidadMedicion;
    }
    public Unidadesmediciones(String unidadMedicion, String descripcion, Set<Detallesproductos> detallesproductoses) {
       this.unidadMedicion = unidadMedicion;
       this.descripcion = descripcion;
       this.detallesproductoses = detallesproductoses;
    }
   
    public Integer getClaveUnidadMedicion() {
        return this.claveUnidadMedicion;
    }
    
    public void setClaveUnidadMedicion(Integer claveUnidadMedicion) {
        this.claveUnidadMedicion = claveUnidadMedicion;
    }
    public String getUnidadMedicion() {
        return this.unidadMedicion;
    }
    
    public void setUnidadMedicion(String unidadMedicion) {
        this.unidadMedicion = unidadMedicion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Detallesproductos> getDetallesproductoses() {
        return this.detallesproductoses;
    }
    
    public void setDetallesproductoses(Set<Detallesproductos> detallesproductoses) {
        this.detallesproductoses = detallesproductoses;
    }




}


