/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ModuloUsuario;

import Clases.ImagenFondo;
import Model.Usuarios;
import View.ModuloUsuario.Opcion.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alonso
 */
public class PrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUsuario
     */
    public PrincipalUsuario() {
        initComponents();
        ocultar();
        deshabilitarCambioContraseña();
        deshabilitarCambioPregunta();
        fondo();
    }

    void ocultar(){
        prinicipaljPanel.setVisible(false);
        menujDesktopPane.setVisible(false);
        guardarPreguntajButton.setVisible(false);
        guardarcontraseñajButton.setVisible(false);
    }
    public void fondo()
    {
        menujDesktopPane.setBorder(new ImagenFondo());
    }
    void limpiar()
    {
        menujDesktopPane.removeAll();
        menujDesktopPane.repaint();
    }
    void hablilitarCambioContraseña()
    {
        actualjPasswordField.setEnabled(true);
        nuevajPasswordField.setEnabled(true);
        confirmarjPasswordField.setEnabled(true);
    }
    void deshabilitarCambioContraseña()
    {
        actualjPasswordField.setEnabled(false);
        nuevajPasswordField.setEnabled(false);
        confirmarjPasswordField.setEnabled(false);
    }
    void deshabilitarCambioPregunta()
    {
        preguntajComboBox.setEnabled(false);
        respuestajTextField.setEnabled(false);
    }
    void habilitarCambioPregunta()
    {
        preguntajComboBox.setEnabled(true);
        respuestajTextField.setEnabled(true);
    }
    Usuarios busqueda ()
    {
    Usuarios busqueda = Controller.UsuarioController.UnicoUsuario(usuariojTextField.getText());
    return busqueda;
    }
    void limpiarPassword()
    {
        actualjPasswordField.setText("");
        nuevajPasswordField.setText("");
        confirmarjPasswordField.setText("");
    }
    void limpiarRespuesta()
    {
        preguntajComboBox.setSelectedIndex(0);
        respuestajTextField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        prinicipaljPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usuariojTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cambiarjPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cambiarjRadioButton = new javax.swing.JRadioButton();
        nocambiarjRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        guardarcontraseñajButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        preguntajComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        respuestajTextField = new javax.swing.JTextField();
        guardarPreguntajButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        preguntaSijRadioButton = new javax.swing.JRadioButton();
        preguntaNojRadioButton = new javax.swing.JRadioButton();
        actualjPasswordField = new javax.swing.JPasswordField();
        nuevajPasswordField = new javax.swing.JPasswordField();
        confirmarjPasswordField = new javax.swing.JPasswordField();
        contraseñajPasswordField = new javax.swing.JPasswordField();
        menujDesktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        añadirUsuariojMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal Usuario");
        setResizable(false);

        prinicipaljPanel.setBackground(new java.awt.Color(163, 220, 236));
        prinicipaljPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Información de Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/Checkmark.png"))); // NOI18N
        jButton1.setText("Accesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cambiarjPanel.setBackground(new java.awt.Color(163, 220, 236));

        jLabel5.setText("Cambira Contraseña:");

        buttonGroup1.add(cambiarjRadioButton);
        cambiarjRadioButton.setText("Si");
        cambiarjRadioButton.setOpaque(false);
        cambiarjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarjRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nocambiarjRadioButton);
        nocambiarjRadioButton.setText("No");
        nocambiarjRadioButton.setOpaque(false);
        nocambiarjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocambiarjRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña actual:");

        jLabel7.setText("Nueva Contraseña:");

        jLabel8.setText("Confirmar Contraseña:");

        guardarcontraseñajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/Valid.png"))); // NOI18N
        guardarcontraseñajButton.setText("Guardar");
        guardarcontraseñajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcontraseñajButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Cambiar Pregunta de Seguridad:");

        preguntajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una pregunta", "Lugar de nacimiento de tu madre", "Mejor amigo de tu infancia", "Nombre de tu primera mascota", "Profesor favorito", "Personaje histórico favorito", "Ocupación del abuelo" }));

        jLabel10.setText("Respuesta:");

        guardarPreguntajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/Valid.png"))); // NOI18N
        guardarPreguntajButton.setText("Guardar");
        guardarPreguntajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPreguntajButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Cambiar Pregunta de Seguridad:");

        buttonGroup2.add(preguntaSijRadioButton);
        preguntaSijRadioButton.setText("Si");
        preguntaSijRadioButton.setOpaque(false);
        preguntaSijRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntaSijRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(preguntaNojRadioButton);
        preguntaNojRadioButton.setText("No");
        preguntaNojRadioButton.setOpaque(false);
        preguntaNojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntaNojRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarjPanelLayout = new javax.swing.GroupLayout(cambiarjPanel);
        cambiarjPanel.setLayout(cambiarjPanelLayout);
        cambiarjPanelLayout.setHorizontalGroup(
            cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarjPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preguntaSijRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preguntaNojRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cambiarjPanelLayout.createSequentialGroup()
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cambiarjPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualjPasswordField)
                            .addComponent(nuevajPasswordField)
                            .addGroup(cambiarjPanelLayout.createSequentialGroup()
                                .addComponent(cambiarjRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nocambiarjRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(confirmarjPasswordField)))
                    .addGroup(cambiarjPanelLayout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardarPreguntajButton)
                            .addComponent(guardarcontraseñajButton)
                            .addGroup(cambiarjPanelLayout.createSequentialGroup()
                                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(preguntajComboBox, 0, 206, Short.MAX_VALUE)
                                    .addComponent(respuestajTextField))))))
                .addGap(59, 59, 59))
        );
        cambiarjPanelLayout.setVerticalGroup(
            cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarjPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cambiarjRadioButton)
                    .addComponent(nocambiarjRadioButton))
                .addGap(18, 18, 18)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nuevajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(confirmarjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarcontraseñajButton)
                .addGap(7, 7, 7)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(preguntaSijRadioButton)
                    .addComponent(preguntaNojRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preguntajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cambiarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuestajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarPreguntajButton))
        );

        javax.swing.GroupLayout prinicipaljPanelLayout = new javax.swing.GroupLayout(prinicipaljPanel);
        prinicipaljPanel.setLayout(prinicipaljPanelLayout);
        prinicipaljPanelLayout.setHorizontalGroup(
            prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prinicipaljPanelLayout.createSequentialGroup()
                .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cambiarjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(prinicipaljPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(prinicipaljPanelLayout.createSequentialGroup()
                                .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuariojTextField)
                                    .addComponent(contraseñajPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))))))
                .addContainerGap(538, Short.MAX_VALUE))
        );
        prinicipaljPanelLayout.setVerticalGroup(
            prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prinicipaljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(prinicipaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contraseñajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiarjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        prinicipaljPanel.setBounds(500, 0, 1010, 510);
        jLayeredPane2.add(prinicipaljPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menujDesktopPane.setBounds(250, -70, 1210, 1080);
        jLayeredPane2.add(menujDesktopPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Ima/Fondo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 1510, 1080);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1510, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        añadirUsuariojMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/usuario.png"))); // NOI18N
        añadirUsuariojMenu.setText("Añadir Usuario");
        añadirUsuariojMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirUsuariojMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(añadirUsuariojMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/usuarios.png"))); // NOI18N
        jMenu1.setText("Añadir Sucursal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/actualizar.png"))); // NOI18N
        jMenu2.setText("Cambiar Contraseña");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/inicio.png"))); // NOI18N
        jMenu3.setText("Menu de Inicio");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/ayuda.png"))); // NOI18N
        jMenu4.setText("Ayuda");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirUsuariojMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirUsuariojMenuMouseClicked
        limpiar();
        prinicipaljPanel.setVisible(false);
        menujDesktopPane.setVisible(true);
        ViewUsuario n = new ViewUsuario();
        menujDesktopPane.add(n);
        n.show();
       
    }//GEN-LAST:event_añadirUsuariojMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        menujDesktopPane.setVisible(false);
        cambiarjPanel.setVisible(false);
        prinicipaljPanel.setVisible(true);
        usuariojTextField.setEnabled(true);
        contraseñajPasswordField.setEnabled(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        new AyudaUsuario().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Clases.VistasController.RegresarInicio();
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        limpiar();
        prinicipaljPanel.setVisible(false);
        menujDesktopPane.setVisible(true);
        ViewSucursal n = new ViewSucursal();
        menujDesktopPane.add(n);
        n.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contaseña = new String(contraseñajPasswordField.getPassword());
        if(!usuariojTextField.getText().equalsIgnoreCase("") && !contaseña.equalsIgnoreCase("")){
            
            if(busqueda()!=null)
            {
               if(busqueda().getPassword().equals(contaseña))
               {
                    JOptionPane.showMessageDialog(null, "Acceso Permitido "
                    ,"Permiso Otorgado", JOptionPane.INFORMATION_MESSAGE);
                    cambiarjPanel.setVisible(true);
                    contraseñajPasswordField.setEditable(false);
                    usuariojTextField.setEnabled(false);
               }
               else
               {
                 JOptionPane.showMessageDialog(null, "Verique que "
                    + "que haya escrito bien su contraseña"
                    ,"Contraseña no Valida", JOptionPane.ERROR_MESSAGE);  
               }
                       
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El usuario "+usuariojTextField.getText()
                    + " no existe"+ "\n Verique que "
                    + "que haya escrito bien el usuario"
                    ,"Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cambiarjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarjRadioButtonActionPerformed
        hablilitarCambioContraseña();
        guardarcontraseñajButton.setVisible(true);
    }//GEN-LAST:event_cambiarjRadioButtonActionPerformed

    private void nocambiarjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocambiarjRadioButtonActionPerformed
        deshabilitarCambioContraseña();
        guardarcontraseñajButton.setVisible(false);
    }//GEN-LAST:event_nocambiarjRadioButtonActionPerformed

    private void preguntaSijRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntaSijRadioButtonActionPerformed
        habilitarCambioPregunta();
        guardarPreguntajButton.setVisible(true);
    }//GEN-LAST:event_preguntaSijRadioButtonActionPerformed

    private void preguntaNojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntaNojRadioButtonActionPerformed
        deshabilitarCambioPregunta();
        limpiarRespuesta();
        guardarPreguntajButton.setVisible(false);
    }//GEN-LAST:event_preguntaNojRadioButtonActionPerformed

    private void guardarcontraseñajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcontraseñajButtonActionPerformed
        String actual = new String(actualjPasswordField.getPassword());
        if(!actual.equalsIgnoreCase(""))
        {
                String nueva = new String(nuevajPasswordField.getPassword())
                ,confirmar = new String(confirmarjPasswordField.getPassword());
              if(!nueva.equalsIgnoreCase("") && !confirmar.equalsIgnoreCase(""))
              {
                        if(busqueda().getPassword().equals(actual))
                        {
                            if(nueva.equals(confirmar))
                            {
                                    if(Controller.UsuarioController.UpdateUsuario
                                            (busqueda().getUsername(), 
                                             nueva,
                                             busqueda().getTipo(), 
                                             busqueda().getPreguntaSeguridad(),
                                             busqueda().getRespuesta(),
                                             busqueda().getSucursales())==true)
                                    {
                                        JOptionPane.showMessageDialog(null, "Contraseña guardada"
                                                          ,"Cambios aplicados", 
                                                          JOptionPane.INFORMATION_MESSAGE);
                                        deshabilitarCambioContraseña();
                                        limpiarPassword();
                                        nocambiarjRadioButton.setSelected(true);
                                        cambiarjRadioButton.setSelected(false);

                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "No se ha podido guardar"
                                                + "\n intente nuevamente"
                                    ,"Error al guardar", JOptionPane.ERROR_MESSAGE); 
                                    }
                            }
                            else
                            {
                              JOptionPane.showMessageDialog(null, "Las contraseñas no son iguales "
                                 ,"Contraseñas diferentes", JOptionPane.ERROR_MESSAGE);  
                            }
                        }
                        else
                        {
                           JOptionPane.showMessageDialog(null, "Error no ha ingresado su "
                                 + "contraseña actual"
                                 ,"Error de Contraseña", JOptionPane.ERROR_MESSAGE);  
                        }
              }
              else
              {
                  JOptionPane.showMessageDialog(null, "No puede dejar campos vacios "
                       ,"Error", JOptionPane.ERROR_MESSAGE);
              }
                
        }
            else
        {
            JOptionPane.showMessageDialog(null, "Ingrese su contaseña "
                     + "actual"
                     ,"Contraseña no Valida", JOptionPane.ERROR_MESSAGE);  
        }
            
    }//GEN-LAST:event_guardarcontraseñajButtonActionPerformed

    private void guardarPreguntajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPreguntajButtonActionPerformed
        if(preguntajComboBox.getSelectedIndex()!=0)
        {
            if(!respuestajTextField.getText().equalsIgnoreCase(""))
            {
                if(Controller.UsuarioController.UpdateUsuario(
                        busqueda().getUsername(), 
                        busqueda().getPassword(),
                        busqueda().getTipo(),
                        preguntajComboBox.getSelectedItem().toString(), 
                        respuestajTextField.getText(),
                        busqueda().getSucursales())==true)
                {
                    JOptionPane.showMessageDialog(null, "Cambios aplicados"
                     ,"Guardar", JOptionPane.INFORMATION_MESSAGE);
                    limpiarRespuesta();
                    preguntaNojRadioButton.setSelected(true);
                    preguntaSijRadioButton.setSelected(false);
                    guardarPreguntajButton.setVisible(false);
                    deshabilitarCambioPregunta();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error al guardar intente nuevamente"
                     ,"Intente nuevamente", JOptionPane.ERROR_MESSAGE);    
                }
            }
            else
            {
                    JOptionPane.showMessageDialog(null, "Tienes que ingresar "
                            + "una respuesta "
                     ,"Respuesta invalida", JOptionPane.ERROR_MESSAGE);  
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Tienes que elegir una pregunta "
                     ,"Opcion no valida", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_guardarPreguntajButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField actualjPasswordField;
    private javax.swing.JMenu añadirUsuariojMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cambiarjPanel;
    private javax.swing.JRadioButton cambiarjRadioButton;
    private javax.swing.JPasswordField confirmarjPasswordField;
    private javax.swing.JPasswordField contraseñajPasswordField;
    private javax.swing.JButton guardarPreguntajButton;
    private javax.swing.JButton guardarcontraseñajButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane menujDesktopPane;
    private javax.swing.JRadioButton nocambiarjRadioButton;
    private javax.swing.JPasswordField nuevajPasswordField;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JRadioButton preguntaNojRadioButton;
    private javax.swing.JRadioButton preguntaSijRadioButton;
    private javax.swing.JComboBox preguntajComboBox;
    private javax.swing.JPanel prinicipaljPanel;
    private javax.swing.JTextField respuestajTextField;
    private javax.swing.JTextField usuariojTextField;
    // End of variables declaration//GEN-END:variables
}
